config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  resources :notes
  
  devise_for :users
  resources :courses
  resources :degrees
  # resources :appointments

  resources :users#, :except => [:create, :new]

   resources :users do                                                                                                                                                           
     resources :appointments
   end
 
  root to: "pages#index"
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :cas_authenticatable, :trackable
  has_and_belongs_to_many :roles
  has_many :appointments

  validates :username, presence: true
  validates :email, presence: true
  validates :role_ids, presence: true


  def self.get_advisors
    role = Role.find_by(:name =>"Advisor")
    # User.where(role_id: role.id).all
    User.joins(:roles).where("roles_users.role_id is #{role.id}")
  end
  

  # Get open times. Queries the appointments table to retrieve
  # time slots available for a given user Assume you want times from 8-5 M-F.
  # 
  # Returns a list of times in the form of Time objects (for now).
  #
  def self.get_availablities(advisor_id, start_t, end_t)

    if Appointment.find_by(user_id=advisor_id).nil?
      "free"
    else
      Appointment.find_by(user_id=advisor_id)
      # [Time.utc(2015,11,17,8,15)]
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # authorize_resource


  
  def index
    @users = User.all
  end


  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # since at this point we dont really care about the validation of creds
      # we can do this or soemthing else

      redirect_to(@user, :notice => 'User was successfully created.')
      redirect_to(new_user_session_path)
    else
      render :action => "new" 
    end
    
  end

  def update
    # @user = current_user

    if @user.update_attributes(user_params)
      #UserMailer.send_signup_email(@user).deliver
      redirect_to(@user, :notice => 'User was successfully updated.') 
    else
      render :action => "edit"

    end

  end


  def destroy
    # @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(:controller => "pages") }
    end
  end

  private

  
  def set_user
    @user = User.find(params[:id])
    # if @user.roles.size == 0
    #   @roles = Role.all
    # else
    #   @roles = @user.roles
    # end
    # @roles = Role.all

  end
  
  def user_params
    # note the nested array param!!!!!!
    params.require(:user).permit(:username,
                                 :email,
                                 :role_ids => [])
  end

end

app/views/users/_form.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= form_for([@user], :html => {:class => "form"}) do |f| %>

    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this transaction from being saved:</h2>

        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    
    <div class="form-group">
      <%= f.label :username, :class => "sr-only"%>
      <%= f.text_field :username, :class => "form-control", :placeholder => "Username"%>
    </div>


    <div class="form-group">
      <%= f.label :email, :class => "sr-only"%>
      <%= f.text_field :email, :class => "form-control", :placeholder => "Email"%>
    </div>


    <div class="form-group">
      <%= f.collection_check_boxes :role_ids, Role.all, :id, :name, {}, {class: :"checkbox"} %>
    </div>
    

    <%= f.submit "Submit", :class => "btn btn-default" %>
    <%#= link_to "Delete", transaction_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger pull-right" %>        
  <% end %>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing #{@user.username}" %>
<div class="main-title">Editing <%= @user.username %></div>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Is Admin?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<%#= render 'form' %>

<!-- Need to figure out the structure of this page and how
     we should lay this out-->
<div class="col-md-6 col-md-offset-3">
  <div style="margin-top: 10px">
    <%= link_to "Sign in with CAS", new_user_session_path(@user), :class => "btn btn-success" %>
  </div>
</div>

app/views/users/show.html.erb
<p>
  <b>Username:</b>
  <%= @user.username %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>