config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  resources :notes
  
  devise_for :users
  resources :courses
  resources :degrees
  # resources :appointments

  resources :users#, :except => [:create, :new]

   resources :users do                                                                                                                                                           
     resources :appointments
   end
 
  root to: "pages#index"
 
end

app/models/degree.rb
class Degree < ActiveRecord::Base
  has_and_belongs_to_many :course
  
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  before_action :set_degree, only: [:show, :edit, :update, :destroy]
  authorize_resource
  
  # GET /degrees
  # GET /degrees.json
  def index
    @degrees = Degree.all
  end

  # GET /degrees/1
  # GET /degrees/1.json
  def show
  end

  # GET /degrees/new
  def new
    @degree = Degree.new
  end

  # GET /degrees/1/edit
  def edit
  end

  # POST /degrees
  # POST /degrees.json
  def create
    @degree = Degree.new(degree_params)

    respond_to do |format|
      if @degree.save
        format.html { redirect_to @degree, notice: 'Degree was successfully created.' }
        format.json { render :show, status: :created, location: @degree }
      else
        format.html { render :new }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /degrees/1
  # PATCH/PUT /degrees/1.json
  def update
    respond_to do |format|
      if @degree.update(degree_params)
        format.html { redirect_to @degree, notice: 'Degree was successfully updated.' }
        format.json { render :show, status: :ok, location: @degree }
      else
        format.html { render :edit }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /degrees/1
  # DELETE /degrees/1.json
  def destroy
    @degree.destroy
    respond_to do |format|
      format.html { redirect_to degrees_url, notice: 'Degree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_degree
      @degree = Degree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def degree_params
      params.require(:degree).permit(:name, :document, :college)
    end
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/views/degrees/_form.html.erb
<%= form_for(@degree) do |f| %>
  <% if @degree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@degree.errors.count, "error") %> prohibited this degree from being saved:</h2>

      <ul>
      <% @degree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :college %><br>
    <%= f.text_field :college %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/degrees/edit.html.erb
<h1>Editing Degree</h1>

<%= render 'form' %>

<%= link_to 'Show', @degree %> |
<%= link_to 'Back', degrees_path %>

app/views/degrees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Degrees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Document</th>
      <th>College</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @degrees.each do |degree| %>
      <tr>
        <td><%= degree.name %></td>
        <td><%= degree.document %></td>
        <td><%= degree.college %></td>
        <td><%= link_to 'Show', degree %></td>
        <td><%= link_to 'Edit', edit_degree_path(degree) %></td>
        <td><%= link_to 'Destroy', degree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Degree', new_degree_path %>

app/views/degrees/new.html.erb
<h1>New Degree</h1>

<%= render 'form' %>

<%= link_to 'Back', degrees_path %>

app/views/degrees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @degree.name %>
</p>

<p>
  <strong>Document:</strong>
  <%= @degree.document %>
</p>

<p>
  <strong>College:</strong>
  <%= @degree.college %>
</p>

<%= link_to 'Edit', edit_degree_path(@degree) %> |
<%= link_to 'Back', degrees_path %>