config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  resources :notes
  
  devise_for :users
  resources :courses
  resources :degrees
  # resources :appointments

  resources :users#, :except => [:create, :new]

   resources :users do                                                                                                                                                           
     resources :appointments
   end
 
  root to: "pages#index"
 
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :user
  belongs_to :note
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @appointments = current_user.appointments
  end


  def show
  end


  def new
    @appointment = current_user.appointments.new
  end


  def edit
  end


  def create
    @appointment = current_user.appointments.new(appointment_params)
    @current_user = current_user
    advisor_name = @appointment[:user_id]
    puts advisor_name
    @advisor = User.get_advisors.find_by_username(advisor_name)
    respond_to do |format|
      if @appointment.save
        #UserMailer.send_appointment_email(@appointment,@current_user).deliver_now
        UserMailer.meeting_request_with_calendar(@current_user,@appointment).deliver_now
        #UserMailer.add_interaction(@current_user).deliver_now
        #format.html { redirect_to current_user, notice: 'Successfully created appointment' }
        format.html { redirect_to current_user, notice: advisor_name }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to current_user, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:user, :student, :start_time, :end_time, :note)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for([@current_user, @appointment]) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% @appointment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
       <%#= f.label :student %><br>
       <%#= f.text_field :student_id %>
       </div>
     -->
  <!-- <div class="field">
       <%#= f.label :note %><br>
       <%#= f.text_field :note_id %>
       </div> -->
  
  <div class="form-group">
    <%= f.label :advisor %> 
    <%= f.collection_select :user_id, User.get_advisors, :id, :username, {}, {:class => "form-control"} %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", :class => "btn" %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing appointments</h1>

<table border="1">
  <thead>
    <tr>
      <th>Appointment_id</th>
      <th>Date</th>
      <th>Start tme</th>
      <th>End Time</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.id %></td>
        <td><%= appointment.start_time.to_date %></td>
        <td><%= appointment.start_time.to_s(:time) %></td>
        <td><%= appointment.end_time.to_s(:time) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New appointment', new_user_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Credit:</strong>
  <%= @appointment.student_id %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @appointment.user_id %>
</p>

<%= link_to 'Edit', edit_user_appointments_path(@appointment) %> |
<%= link_to 'Back', user_appointments_path %>